version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: devops-backend
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOSTNAME=0.0.0.0
      # Database envs (if/when backend uses them)
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=devopsinterview
      - DB_USER=admin
      - DB_PASSWORD=devpassword
      # Redis envs (if/when backend uses them)
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: devops-frontend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Expose backend URL to the app if needed
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:14
    container_name: devops-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=devopsinterview
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: devops-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
